version: 2
jobs:
  build:
    docker:
      - image: elixir:latest
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix test
